/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.telas;

import br.com.controller.ControllerCidade;
import br.com.controller.ControllerFuncionario;
import br.com.model.ModelFuncionario;
import br.com.util.Uteis;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author catuai
 */
public class CadFuncionario extends javax.swing.JInternalFrame {

    Uteis uteis = new Uteis();
    int i = 0;

    /**
     * Creates new form CadFornecedor
     */
    public CadFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pessoaf = new javax.swing.JPanel();
        id1 = new javax.swing.JLabel();
        txtIdf = new javax.swing.JTextField();
        nome1 = new javax.swing.JLabel();
        txtNomef = new javax.swing.JTextField();
        cpf1 = new javax.swing.JLabel();
        txtTelff = new javax.swing.JFormattedTextField();
        telefone1 = new javax.swing.JLabel();
        txtEmailf = new javax.swing.JTextField();
        txtCpff = new javax.swing.JFormattedTextField();
        email1 = new javax.swing.JLabel();
        Enderecof = new javax.swing.JPanel();
        endereco1 = new javax.swing.JLabel();
        txtEnderecof = new javax.swing.JTextField();
        num1 = new javax.swing.JLabel();
        txtNumf = new javax.swing.JTextField();
        bairro1 = new javax.swing.JLabel();
        cidade1 = new javax.swing.JLabel();
        txtBairrof = new javax.swing.JTextField();
        uf1 = new javax.swing.JLabel();
        txtUFf = new javax.swing.JTextField();
        txtCepf = new javax.swing.JFormattedTextField();
        cep1 = new javax.swing.JLabel();
        CbxCidadef = new javax.swing.JComboBox<>();
        BtnSalvar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Funcionario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCargof = new javax.swing.JTextField();
        txtSalariof = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro Funcionario");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        Pessoaf.setBorder(javax.swing.BorderFactory.createTitledBorder("Funcionario"));

        id1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        id1.setText("ID");

        txtIdf.setEditable(false);

        nome1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nome1.setText("Nome");

        cpf1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cpf1.setText("CPF");

        try {
            txtTelff.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        telefone1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        telefone1.setText("Telefone");

        try {
            txtCpff.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        email1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        email1.setText("Email");

        javax.swing.GroupLayout PessoafLayout = new javax.swing.GroupLayout(Pessoaf);
        Pessoaf.setLayout(PessoafLayout);
        PessoafLayout.setHorizontalGroup(
            PessoafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PessoafLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PessoafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PessoafLayout.createSequentialGroup()
                        .addGroup(PessoafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email1)
                            .addComponent(txtEmailf, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PessoafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PessoafLayout.createSequentialGroup()
                                .addComponent(telefone1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PessoafLayout.createSequentialGroup()
                                .addComponent(txtTelff)
                                .addContainerGap())))
                    .addGroup(PessoafLayout.createSequentialGroup()
                        .addGroup(PessoafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id1)
                            .addComponent(txtIdf, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PessoafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomef, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nome1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PessoafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PessoafLayout.createSequentialGroup()
                                .addComponent(cpf1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PessoafLayout.createSequentialGroup()
                                .addComponent(txtCpff, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        PessoafLayout.setVerticalGroup(
            PessoafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PessoafLayout.createSequentialGroup()
                .addGroup(PessoafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id1)
                    .addComponent(nome1)
                    .addComponent(cpf1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PessoafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PessoafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email1)
                    .addComponent(telefone1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PessoafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Enderecof.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        endereco1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        endereco1.setText("Endereço");

        num1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        num1.setText("Número");

        bairro1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bairro1.setText("Bairro");

        cidade1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cidade1.setText("Cidade");

        uf1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        uf1.setText("UF");

        txtUFf.setEditable(false);

        try {
            txtCepf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cep1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cep1.setText("CEP");

        CbxCidadef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        CbxCidadef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxCidadefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EnderecofLayout = new javax.swing.GroupLayout(Enderecof);
        Enderecof.setLayout(EnderecofLayout);
        EnderecofLayout.setHorizontalGroup(
            EnderecofLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnderecofLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EnderecofLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnderecofLayout.createSequentialGroup()
                        .addGroup(EnderecofLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBairrof, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bairro1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(EnderecofLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUFf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uf1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(EnderecofLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCepf, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cep1))
                        .addGap(18, 18, 18)
                        .addGroup(EnderecofLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EnderecofLayout.createSequentialGroup()
                                .addComponent(num1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtNumf, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
                    .addGroup(EnderecofLayout.createSequentialGroup()
                        .addGroup(EnderecofLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEnderecof, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endereco1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(EnderecofLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EnderecofLayout.createSequentialGroup()
                                .addComponent(cidade1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(CbxCidadef, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        EnderecofLayout.setVerticalGroup(
            EnderecofLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnderecofLayout.createSequentialGroup()
                .addGroup(EnderecofLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endereco1)
                    .addComponent(cidade1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EnderecofLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEnderecof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbxCidadef, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EnderecofLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairro1)
                    .addComponent(uf1)
                    .addComponent(cep1)
                    .addComponent(num1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EnderecofLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairrof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUFf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCepf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/images/Apply.png"))); // NOI18N
        BtnSalvar.setText("Salvar");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/images/Trash.png"))); // NOI18N
        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Funcionario.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargo/Salario"));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Cargo");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Salario");

        txtSalariof.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));

        javax.swing.GroupLayout FuncionarioLayout = new javax.swing.GroupLayout(Funcionario);
        Funcionario.setLayout(FuncionarioLayout);
        FuncionarioLayout.setHorizontalGroup(
            FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FuncionarioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FuncionarioLayout.createSequentialGroup()
                        .addComponent(txtCargof, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtSalariof, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FuncionarioLayout.setVerticalGroup(
            FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FuncionarioLayout.createSequentialGroup()
                .addGroup(FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCargof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalariof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pessoaf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Enderecof, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pessoaf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Enderecof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(this,
                    "Deseja Realmente Salvar?",
                    "Salvar",
                    JOptionPane.YES_NO_OPTION)
                    == JOptionPane.YES_OPTION) {
                adicionarFunc();
            }
        } catch (HeadlessException | SQLException ex) {
            Logger.getLogger(CadFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        uteis.limparCampos(Pessoaf);
        uteis.limparCampos(Enderecof);
        uteis.limparCampos(Funcionario);
        Ultimo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CbxCidadefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxCidadefActionPerformed
        // TODO add your handling code here:
        try {
            ControllerCidade cidad = new ControllerCidade();
            ResultSet rs = cidad.listarCidades();

            while (rs.next()) {
                String city = rs.getString(2);
                if (city.equals(CbxCidadef.getSelectedItem())) {
                    txtUFf.setText(rs.getString(3));
                    i = rs.getInt(1);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_CbxCidadefActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        DadosCbx();
        Ultimo();
        this.txtNomef.requestFocus();
    }//GEN-LAST:event_formInternalFrameActivated

    private void adicionarFunc() throws SQLException {
        try {
            ModelFuncionario func = new ModelFuncionario();

            ControllerFuncionario contFunc = new ControllerFuncionario(this);

            func.setPessoanome(txtNomef.getText());
            func.setPessoaCPF(txtCpff.getText());
            func.setPessoaEmail(txtEmailf.getText());
            func.setPessoaTele(txtTelff.getText());
            func.setRua(txtEnderecof.getText());
            func.setNumero(txtNumf.getText());
            func.setBairro(txtBairrof.getText());
            func.setCep(txtCepf.getText());
            func.setIdCidade(i);
            func.setCargo(txtCargof.getText());
            func.setSalario(txtSalariof.getText());

            contFunc.adicionarFun(func);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    Vector<Integer> IdCidade = new Vector<>();

    public void DadosCbx() {
        try {
            ControllerCidade cidade = new ControllerCidade();
            ResultSet rs = cidade.listarCidades();

            while (rs.next()) {
                IdCidade.addElement(rs.getInt(1));
                CbxCidadef.addItem(rs.getString(2));
            }
        } catch (SQLException e) {

        }
    }

    public void Ultimo() {
        try {
            ControllerFuncionario person = new ControllerFuncionario(this);
            ResultSet rs = person.ultimoElemento();
            while (rs.next()) {
                int n = rs.getInt(1);
                String str = Integer.toString(n);
                txtIdf.setText(str);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JComboBox<String> CbxCidadef;
    public javax.swing.JPanel Enderecof;
    public javax.swing.JPanel Funcionario;
    public javax.swing.JPanel Pessoaf;
    private javax.swing.JLabel bairro1;
    private javax.swing.JLabel cep1;
    private javax.swing.JLabel cidade1;
    private javax.swing.JLabel cpf1;
    private javax.swing.JLabel email1;
    private javax.swing.JLabel endereco1;
    private javax.swing.JLabel id1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nome1;
    private javax.swing.JLabel num1;
    private javax.swing.JLabel telefone1;
    private javax.swing.JTextField txtBairrof;
    private javax.swing.JTextField txtCargof;
    private javax.swing.JFormattedTextField txtCepf;
    private javax.swing.JFormattedTextField txtCpff;
    private javax.swing.JTextField txtEmailf;
    private javax.swing.JTextField txtEnderecof;
    private javax.swing.JTextField txtIdf;
    private javax.swing.JTextField txtNomef;
    private javax.swing.JTextField txtNumf;
    private javax.swing.JFormattedTextField txtSalariof;
    private javax.swing.JFormattedTextField txtTelff;
    private javax.swing.JTextField txtUFf;
    private javax.swing.JLabel uf1;
    // End of variables declaration//GEN-END:variables
}
