/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.telas;

import br.com.util.PosicaoFormulario;
import java.text.DateFormat;
import java.util.Date;

/**
 *
 * @author catuai
 */
public class Menu extends javax.swing.JFrame {

    PosicaoFormulario form = new PosicaoFormulario();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        //setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopMenu = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        txtData = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFinan = new javax.swing.JMenu();
        menuAbertCaixa = new javax.swing.JMenuItem();
        menuContPagar = new javax.swing.JMenuItem();
        menuContReceber = new javax.swing.JMenuItem();
        menuCadPagamento = new javax.swing.JMenuItem();
        menuConsultaConta = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        MenuCadCliente = new javax.swing.JMenuItem();
        menuCadFornec = new javax.swing.JMenuItem();
        menuProd = new javax.swing.JMenu();
        menuCadProd = new javax.swing.JMenuItem();
        menuPrecoProd = new javax.swing.JMenuItem();
        menuConsultaProd = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        menuEntraEstoq = new javax.swing.JMenuItem();
        menuDevEstoq = new javax.swing.JMenuItem();
        menuConsultaEstoq = new javax.swing.JMenuItem();
        menuVenda = new javax.swing.JMenu();
        menuPedido = new javax.swing.JMenuItem();
        menuConsultaPedido = new javax.swing.JMenuItem();
        menuGarantia = new javax.swing.JMenuItem();
        menuOS = new javax.swing.JMenu();
        menuCriarOS = new javax.swing.JMenuItem();
        menuListServ = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("menu"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout DesktopMenuLayout = new javax.swing.GroupLayout(DesktopMenu);
        DesktopMenu.setLayout(DesktopMenuLayout);
        DesktopMenuLayout.setHorizontalGroup(
            DesktopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
        );
        DesktopMenuLayout.setVerticalGroup(
            DesktopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );

        txtData.setText("data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtData)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtData))
        );

        jMenuBar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuFinan.setText("Financeiro");
        menuFinan.setEnabled(false);
        menuFinan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuAbertCaixa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuAbertCaixa.setText("Abertura de Caixa");
        menuFinan.add(menuAbertCaixa);

        menuContPagar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuContPagar.setText("Contas a Pagar");
        menuFinan.add(menuContPagar);

        menuContReceber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuContReceber.setText("Contas a Receber");
        menuFinan.add(menuContReceber);

        menuCadPagamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuCadPagamento.setText("Cadastro Forma de Pagamento");
        menuFinan.add(menuCadPagamento);

        menuConsultaConta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuConsultaConta.setText("Consultar Contas");
        menuFinan.add(menuConsultaConta);

        jMenuBar1.add(menuFinan);

        menuCliente.setText("Pessoa");
        menuCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuClienteMouseClicked(evt);
            }
        });

        MenuCadCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        MenuCadCliente.setText("Cadastro de Cliente");
        MenuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadClienteActionPerformed(evt);
            }
        });
        menuCliente.add(MenuCadCliente);

        menuCadFornec.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuCadFornec.setText("Cadastro Fornecedor");
        menuCadFornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFornecActionPerformed(evt);
            }
        });
        menuCliente.add(menuCadFornec);

        jMenuBar1.add(menuCliente);

        menuProd.setText("Produto");
        menuProd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuCadProd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuCadProd.setText("Cadastro de Produto");
        menuProd.add(menuCadProd);

        menuPrecoProd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuPrecoProd.setText("Preço Produto");
        menuProd.add(menuPrecoProd);

        menuConsultaProd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuConsultaProd.setText("Consulta Produto");
        menuProd.add(menuConsultaProd);

        jMenuBar1.add(menuProd);

        menuEstoque.setText("Estoque");
        menuEstoque.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuEntraEstoq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuEntraEstoq.setText("Entrada Estoque");
        menuEstoque.add(menuEntraEstoq);

        menuDevEstoq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuDevEstoq.setText("Devolução Estoque");
        menuEstoque.add(menuDevEstoq);

        menuConsultaEstoq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuConsultaEstoq.setText("Consulta Estoque");
        menuEstoque.add(menuConsultaEstoq);

        jMenuBar1.add(menuEstoque);

        menuVenda.setText("Venda");
        menuVenda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuPedido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuPedido.setText("Digitação de Pedido");
        menuVenda.add(menuPedido);

        menuConsultaPedido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuConsultaPedido.setText("Consulta Pedido");
        menuVenda.add(menuConsultaPedido);

        menuGarantia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuGarantia.setText("Controle Garantia");
        menuVenda.add(menuGarantia);

        jMenuBar1.add(menuVenda);

        menuOS.setText("Ordem Serviço");
        menuOS.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuCriarOS.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuCriarOS.setText("Criar OS");
        menuOS.add(menuCriarOS);

        menuListServ.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuListServ.setText("Lista de Serviços");
        menuOS.add(menuListServ);

        jMenuBar1.add(menuOS);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopMenu)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DesktopMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuClienteMouseClicked

    private void MenuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadClienteActionPerformed
        // TODO add your handling code here:
        //CadCliente cad = new CadCliente();
        //this.DesktopMenu.add(cad);
        //cad.setVisible(true);
        CadPessoa cad;
        form.abrirFormulario(cad = new CadPessoa(), DesktopMenu);
    }//GEN-LAST:event_MenuCadClienteActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        txtData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void menuCadFornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFornecActionPerformed
        // TODO add your handling code here:
        CadFornecedor fornec;
        form.abrirFormulario(fornec = new CadFornecedor(), DesktopMenu);
    }//GEN-LAST:event_menuCadFornecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopMenu;
    private javax.swing.JMenuItem MenuCadCliente;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem menuAbertCaixa;
    private javax.swing.JMenuItem menuCadFornec;
    private javax.swing.JMenuItem menuCadPagamento;
    private javax.swing.JMenuItem menuCadProd;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenuItem menuConsultaConta;
    private javax.swing.JMenuItem menuConsultaEstoq;
    private javax.swing.JMenuItem menuConsultaPedido;
    private javax.swing.JMenuItem menuConsultaProd;
    private javax.swing.JMenuItem menuContPagar;
    private javax.swing.JMenuItem menuContReceber;
    private javax.swing.JMenuItem menuCriarOS;
    private javax.swing.JMenuItem menuDevEstoq;
    private javax.swing.JMenuItem menuEntraEstoq;
    private javax.swing.JMenu menuEstoque;
    public static javax.swing.JMenu menuFinan;
    private javax.swing.JMenuItem menuGarantia;
    private javax.swing.JMenuItem menuListServ;
    private javax.swing.JMenu menuOS;
    private javax.swing.JMenuItem menuPedido;
    private javax.swing.JMenuItem menuPrecoProd;
    private javax.swing.JMenu menuProd;
    private javax.swing.JMenu menuVenda;
    private javax.swing.JLabel txtData;
    // End of variables declaration//GEN-END:variables
}
