/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.telas;

import br.com.conexao.ModelConexao;
import br.com.util.Uteis;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author catuai
 */
public class Menu extends javax.swing.JFrame {

    Connection conexao = null;
    Uteis form = new Uteis();
    CadPessoa CDP = new CadPessoa();

    /**
     * Creates new form Menu
     *
     * @throws java.sql.SQLException
     */
    public Menu() throws SQLException {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/br/com/images/ico.ico")).getImage());
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/images/Menu.png"));
        Image image = icon.getImage();
        DesktopMenu = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(), getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFinan = new javax.swing.JMenu();
        menuAbertCaixa = new javax.swing.JMenuItem();
        menuContPagar = new javax.swing.JMenuItem();
        menuContReceber = new javax.swing.JMenuItem();
        menuCadPagamento = new javax.swing.JMenuItem();
        menuConsultaConta = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        RelClient = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        MenuCadCliente = new javax.swing.JMenuItem();
        menuCadFornec = new javax.swing.JMenuItem();
        menuProd = new javax.swing.JMenu();
        menuCadProd = new javax.swing.JMenuItem();
        menuConsultaProd = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        menuEntraEstoq = new javax.swing.JMenuItem();
        menuDevEstoq = new javax.swing.JMenuItem();
        menuConsultaEstoq = new javax.swing.JMenuItem();
        menuVenda = new javax.swing.JMenu();
        menuPedido = new javax.swing.JMenuItem();
        menuConsultaPedido = new javax.swing.JMenuItem();
        menuGarantia = new javax.swing.JMenuItem();
        menuOS = new javax.swing.JMenu();
        menuCriarOS = new javax.swing.JMenuItem();
        menuListServ = new javax.swing.JMenuItem();
        jMenu = new javax.swing.JMenu();
        Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tech. Torres - Menu");
        setName("menu"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        DesktopMenu.setBackground(new java.awt.Color(102, 102, 102));
        DesktopMenu.setName(""); // NOI18N

        javax.swing.GroupLayout DesktopMenuLayout = new javax.swing.GroupLayout(DesktopMenu);
        DesktopMenu.setLayout(DesktopMenuLayout);
        DesktopMenuLayout.setHorizontalGroup(
            DesktopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
        );
        DesktopMenuLayout.setVerticalGroup(
            DesktopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuFinan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/images/Briefcase.png"))); // NOI18N
        menuFinan.setText("Financeiro");
        menuFinan.setEnabled(false);
        menuFinan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuAbertCaixa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuAbertCaixa.setText("Abertura de Caixa");
        menuFinan.add(menuAbertCaixa);

        menuContPagar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuContPagar.setText("Contas a Pagar");
        menuFinan.add(menuContPagar);

        menuContReceber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuContReceber.setText("Contas a Receber");
        menuFinan.add(menuContReceber);

        menuCadPagamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuCadPagamento.setText("Cadastro Forma de Pagamento");
        menuFinan.add(menuCadPagamento);

        menuConsultaConta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuConsultaConta.setText("Consultar Contas");
        menuFinan.add(menuConsultaConta);

        jMenu1.setText("Relatorios");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        RelClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        RelClient.setText("Clientes");
        RelClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelClientActionPerformed(evt);
            }
        });
        jMenu1.add(RelClient);

        menuFinan.add(jMenu1);

        jMenuBar1.add(menuFinan);

        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/images/People.png"))); // NOI18N
        menuCliente.setText("Pessoa");
        menuCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        MenuCadCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        MenuCadCliente.setText("Cadastro de Cliente");
        MenuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadClienteActionPerformed(evt);
            }
        });
        menuCliente.add(MenuCadCliente);

        menuCadFornec.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuCadFornec.setText("Cadastro Funcionario");
        menuCadFornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFornecActionPerformed(evt);
            }
        });
        menuCliente.add(menuCadFornec);

        jMenuBar1.add(menuCliente);

        menuProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/images/Shopping cart.png"))); // NOI18N
        menuProd.setText("Produto");
        menuProd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuCadProd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuCadProd.setText("Cadastro de Produto");
        menuCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadProdActionPerformed(evt);
            }
        });
        menuProd.add(menuCadProd);

        menuConsultaProd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuConsultaProd.setText("Consulta Produto");
        menuConsultaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaProdActionPerformed(evt);
            }
        });
        menuProd.add(menuConsultaProd);

        jMenuBar1.add(menuProd);

        menuEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/images/Database.png"))); // NOI18N
        menuEstoque.setText("Estoque");
        menuEstoque.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuEntraEstoq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuEntraEstoq.setText("Entrada Estoque");
        menuEstoque.add(menuEntraEstoq);

        menuDevEstoq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuDevEstoq.setText("Devolução Estoque");
        menuEstoque.add(menuDevEstoq);

        menuConsultaEstoq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuConsultaEstoq.setText("Consulta Estoque");
        menuEstoque.add(menuConsultaEstoq);

        jMenuBar1.add(menuEstoque);

        menuVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/images/Buy.png"))); // NOI18N
        menuVenda.setText("Venda");
        menuVenda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuPedido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuPedido.setText("Digitação de Pedido");
        menuPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidoActionPerformed(evt);
            }
        });
        menuVenda.add(menuPedido);

        menuConsultaPedido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuConsultaPedido.setText("Consulta Pedido");
        menuVenda.add(menuConsultaPedido);

        menuGarantia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuGarantia.setText("Controle Garantia");
        menuVenda.add(menuGarantia);

        jMenuBar1.add(menuVenda);

        menuOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/images/Clipboard.png"))); // NOI18N
        menuOS.setText("Ordem Serviço");
        menuOS.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuCriarOS.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuCriarOS.setText("Criar OS");
        menuOS.add(menuCriarOS);

        menuListServ.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuListServ.setText("Lista de Serviços");
        menuOS.add(menuListServ);

        jMenuBar1.add(menuOS);

        jMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/images/Application.png"))); // NOI18N
        jMenu.setText("Conf.");
        jMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        Sair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/images/Exit.png"))); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        jMenu.add(Sair);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopMenu, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadClienteActionPerformed
        CadPessoa cad;
        form.abrirFormulario(cad = new CadPessoa(), DesktopMenu);
    }//GEN-LAST:event_MenuCadClienteActionPerformed

    private void menuCadFornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFornecActionPerformed
        // TODO add your handling code here:
        CadFuncionario func;
        form.abrirFormulario(func = new CadFuncionario(), DesktopMenu);
    }//GEN-LAST:event_menuCadFornecActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        form.sair(this);

    }//GEN-LAST:event_SairActionPerformed

    private void menuCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadProdActionPerformed
        // TODO add your handling code here:
        CadProduto prod;
        form.abrirFormulario(prod = new CadProduto(), DesktopMenu);
    }//GEN-LAST:event_menuCadProdActionPerformed

    private void menuConsultaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaProdActionPerformed
        // TODO add your handling code here:
        ListProd preco;
        form.abrirFormulario(preco = new ListProd(), DesktopMenu);
    }//GEN-LAST:event_menuConsultaProdActionPerformed

    private void RelClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelClientActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this,
                "Confirmar impressão",
                "Atenção",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                conexao = ModelConexao.conector();
                JasperPrint print = JasperFillManager.fillReport(
                        "C:/reports/clientes.jasper",
                        null,
                        conexao);
                //JasperViewer.viewReport(print, false);
                JasperViewer jv = new JasperViewer(print,
                        false);
                jv.setTitle("Relatorio de Clientes");
                jv.setIconImage(new ImageIcon(getClass().getResource("/br/com/images/ico.ico")).getImage());
                jv.setVisible(true);
                ModelConexao.fechaConexao(conexao);
            } catch (SQLException | JRException e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_RelClientActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        form.sair(this);
    }//GEN-LAST:event_formWindowClosing

    private void menuPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidoActionPerformed
        // TODO add your handling code here:
        CadVenda cadv;
        try {
            cadv = new CadVenda(this);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            form.abrirFormulario(cadv = new CadVenda(this), DesktopMenu);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Menu().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane DesktopMenu;
    private javax.swing.JMenuItem MenuCadCliente;
    private javax.swing.JMenuItem RelClient;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAbertCaixa;
    private javax.swing.JMenuItem menuCadFornec;
    private javax.swing.JMenuItem menuCadPagamento;
    private javax.swing.JMenuItem menuCadProd;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenuItem menuConsultaConta;
    private javax.swing.JMenuItem menuConsultaEstoq;
    private javax.swing.JMenuItem menuConsultaPedido;
    private javax.swing.JMenuItem menuConsultaProd;
    private javax.swing.JMenuItem menuContPagar;
    private javax.swing.JMenuItem menuContReceber;
    private javax.swing.JMenuItem menuCriarOS;
    private javax.swing.JMenuItem menuDevEstoq;
    private javax.swing.JMenuItem menuEntraEstoq;
    private javax.swing.JMenu menuEstoque;
    public static javax.swing.JMenu menuFinan;
    private javax.swing.JMenuItem menuGarantia;
    private javax.swing.JMenuItem menuListServ;
    private javax.swing.JMenu menuOS;
    private javax.swing.JMenuItem menuPedido;
    private javax.swing.JMenu menuProd;
    private javax.swing.JMenu menuVenda;
    // End of variables declaration//GEN-END:variables
}
